[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2 --threads 2 --worker-class sync"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10